server:
  port: 4002
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/productdb}
      auto-index-creation: true
jwt:
  secret: ${JWT_SECRET}
management:
  endpoints:
    web:
      exposure:
        include: health